title: Dylan Rollins
logo: /assets/img/logo.png
description: I am a budding, intellecutally-driven data scientist who works with Python, R, and C++. I would love to work together!
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
