title: Dylan Rollins
logo: /assets/img/logo.png

description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an intellecutally-driven third-year undergraduate statistics student who utilizes Python, R, and C++ to solve relevant, real-world problems.
  <br><br>
  Some of my interests include: machine learning, classification algorithms, high-dimensional data analysis, and bayesian classification. My background in computer science allows me to 
  <br><br>
  In my free time, I enjoy taking digital and film **<a href="https://www.linkedin.com/in/example/">photos</a>**.
  
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
