title: Dylan Rollins
logo: /assets/img/logo.png
description: I am a budding, intellecutally-driven third-year undergraduate statistics student who works with Python, R, and C++. My interests include 
I would love to work together!
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
