title: Dylan Rollins
logo: /assets/img/logo.png

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I am an third-year undergraduate statistics student who utilizes Python, R, and C++ to solve relevant, real-world problems.
  <br><br>
  Some of my interests include: machine learning, classification algorithms, high-dimensional data analysis, and bayesian classification. 
  <br><br>
  In my free time, I enjoy taking digital and film photos. My work has been featured by the City of Chicago. <br> Check out my <u><a href="https://dylanrollinss.github.io/photography">photos</a></u>.
  
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
