title: Dylan Rollins
logo: /assets/img/logo.png
description: >
I am a budding, intellecutally-driven third-year bump undergraduate statistics student who works with Python, R, and C++.
<br><br>
hmm work?
<br><br>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
