title: Dylan Rollins
logo: /assets/img/logo.png

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I am an third-year undergraduate statistics student who utilizes Python, R, and C++ to solve relevant, real-world problems—in my opinion, there is nothing more interesting than forming conjecture, then potentially finding data to prove and support it.
  <br><br>
  Some of my interests include: machine learning, classification algorithms, high-dimensional data analysis, and bayesian classification. My background in computer science has allowed me to develop a deeper understanding of some of the popular predictive models; I strive to stay away from the "black-box" method of applying models. 
  <br><br>
  In my free time, I enjoy taking digital and film <u><a href="https://www.linkedin.com/in/example/">photos</a></u>.
  
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
